### ISSUE TITLE
My laptop got hang when run the travel time inversion part code

### ISSUE THREAD

**Issue by ad1995-geek** [gimli-org/example-data#3]
I have one shot and 262 geophone and I have make .sgt file for same. But when run the inversion part, my laptop got hanged. Why it's happening? I tried to increase cellsize but no luck. Please help me.

**Comment by halbmy** [comment]
We will not be able to help you unless you attach your data file and a script that generates the error. 

Please, use the template filling in the informations about the software version, platform etc.

**Comment by ad1995-geek** [comment]
[outnew.txt](https://github.com/gimli-org/example-data/files/7409350/outnew.txt)
this is my data file. please check it.

**Comment by halbmy** [comment]
```
import matplotlib.pyplot as plt
from pygimli.physics import traveltime as tt

data = tt.load("outnew.txt")
print(data)
_, ax = plt.subplots()
tt.drawFirstPicks(ax, data)
```

![image](https://user-images.githubusercontent.com/7136401/138928047-a4bcea5b-9dc4-49d9-b4b0-534b3216fab3.png)

**Comment by ad1995-geek** [comment]
Thank you for reply. But the inversion part which gives the velocity model, is not running. Could you please run the inversion code cell?

**Comment by halbmy** [comment]
```
mgr = tt.TravelTimeManager(data)
mgr.invert()
mgr.showResult()
```
![image](https://user-images.githubusercontent.com/7136401/138937310-f8336bee-635d-4781-b61f-70a81b31b1a9.png)

Of course, a tomography with just one shot does not make much sense.

**Comment by ad1995-geek** [comment]
thank you for the reply. The inversion part running well. 
1) But why it takes lambda value 20 every time?
2)I am not getting matrix plot of apparent velocity. I have attached the image. please check it. why it is showing a black line?
![IMG_20211027_112102](https://user-images.githubusercontent.com/65445781/139019088-8d01d5aa-1235-43a5-a355-6e0195fc5fa7.jpg)

**Comment by halbmy** [comment]
The apparent velocity plot behind `showData` is a crossplot over the shots (y axis) and receivers (x axis). As you only have one shot, you won't see much anyways. Additionally, in your file all data are marked invalid.

**Comment by halbmy** [comment]
The lambda value of 20 is the default (often meaningful), but you can pass another value `mgr.invert(lam=100)`

**Comment by ad1995-geek** [comment]
Thank you for the explanation. Is it possible to have the computed travel time due to the model? If yes, then it would useful to observe/understand the difference between the observed and computed travel time for the data. Kindly let me know. Thanks for your kind support

**Comment by halbmy** [comment]
In your simple case of just one receiver, you can just use
```
_, ax = plt.subplots()
tt.drawFirstPicks(ax, data)
sx = pg.x(data)
gx = sx[data["g"]]
ax.plot(gx, mgr.inv.response, "r")
```
In the more general case, we should expand the function `tt.drawFirstPicks` so that it takes `response=` or a switch that the additional `tt` argument is plotted as response along with `data["t"]`.

**Comment by halbmy** [comment]
That's the output
![image](https://user-images.githubusercontent.com/7136401/139746391-23227a52-dd95-4c41-91f1-5b8aadde9818.png)

**Comment by ad1995-geek** [comment]
> ```
> mgr = tt.TravelTimeManager(data)
> mgr.invert()
> mgr.showResult()
> ```
> 
> ![image](https://user-images.githubusercontent.com/7136401/138937310-f8336bee-635d-4781-b61f-70a81b31b1a9.png)

In this velocity model, why the lower part of the shot point have much error compared to other portion?. How can we minimize it? Do we have change some parameters to improve the velocity model? 
Thank you.

**Comment by halbmy** [comment]
I don't understand your question. What do you mean with "lower part of the shot point"? And I don't get what you mean with error.

From just one shot, you cannot make a 2D tomography and the result is highly ambiguous. Particularly, there is no resolution below the shot.

**Comment by halbmy** [comment]
```
ax, cb = mgr.showResult(coverage=(mgr.coverage()>0))
mgr.drawRayPaths(ax)
```
![image](https://user-images.githubusercontent.com/7136401/141309575-7299fcfd-ac3c-4cb2-b6af-731d3b4c25a6.png)

**Comment by ad1995-geek** [comment]
Thank you for the explanation. It is true that  a single shot point will not give very good 2D tomography. My question was that, why we are getting pretty high ambiguous results in the left side of deeper part of the 2D tomography where velocity is exceptionally high around 22000 m/s ?

**Comment by halbmy** [comment]
A single shot will not give you ANY meaningful tomography.

In the lower left part there is no resolution at all. Due to the smoothness constraints this region will be filled, and as the velocity increases with depth this is also done there.
